theme: jekyll-theme-minimal

title: [Decoding Biases  <br>in AI &mdash; <br><small>Final Project</small>]
description: [<b>Spring 2021<b> <br>Dhakshinamoorthy A.&comma;  Kersys R.&comma;  <br>Kumar G.&comma;  Selous M.]
